# Generated by Django 4.2.16 on 2024-10-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_thread_poster_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-posted_on']},
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='title',
            new_name='heading',
        ),
    ]
