# Generated by Django 4.2.16 on 2024-10-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_response_options_rename_heading_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='visible',
            field=models.IntegerField(choices=[(0, 'Visible'), (1, 'Invisible')], default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='visible',
            field=models.IntegerField(choices=[(0, 'Visible'), (1, 'Invisible')], default=0),
        ),
    ]
