# Generated by Django 4.2.16 on 2024-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_url', models.URLField()),
                ('user_being_reported', models.CharField()),
                ('reason_for_report', models.TextField()),
                ('reporters_email', models.EmailField(max_length=254)),
                ('examined', models.BooleanField(default=False)),
            ],
        ),
    ]
